### ISSUE TITLE
code cleanup and refactoring

### ISSUE THREAD

**Issue by nouse4anick** [scotthibbs/FDLog_Enhanced#10]
I've taken my fork and I've gone all out and moved a lot of stuff around (namely sorted everything to kinda group things together)

What I am aiming to do eventually once I get a refresher in classes and tk is to re-flow the code and make it a bit more modular (so the database is actually a stand alone module with a connection to the network interface). This will allow us to move on to getting a few other projects marked off for this (namely the info booth interface).

I'll let you know when I'm ready to do another pull request but for now lets use this thread as a dumping ground for improvements that need to be done and that you want to see.

Art

**Comment by scotthibbs** [comment]
Art,

There is another group that has forked us.

I don't like that they renamed it just fdlog and took out our names in the
comments... But at least two coders working on it. They are just starting.
Search fdlog enhanced on github to see.

Let me know what you think.

Scott

**Comment by scotthibbs** [comment]
I've moved all the main program to it's own section except for a top level class that wouldn't work without being below the main program. 

As of 05Jul2022 Beta 2.0 this may not be an issue.

If you still want to restructure (I'm not a trained programmer) please reopen an issue.
