### ISSUE TITLE
miniweb.py is broken for win10

### ISSUE THREAD

**Issue by scotthibbs** [scotthibbs/FDLog_Enhanced#15]
Although a separate program, this was used to copy the fdlog files to other computers on the same network without a need to have a usb drive. It wasn't documented or even in mentioned within FDLog but it sure was handy if you knew it was there. 

It imported BaseHTTPServer, SimpleHTTPServer, socket, and sys. 

Starting with Windows 10, Microsoft has implemented a new security feature that will prevent users from grabbing a random port and giving it away to some service. This could occur if you’re using a script or a home brewed application.

We might be able to find a similar program or find how to update it. 
I'll add it to our to-do list.
Scott

**Comment by nouse4anick** [comment]
Those are just libraries that are standard in python 
(https://docs.python.org/2/library/basehttpserver.html)

my understanding is that those set up the back-end and deal with the 
data streams and network stuff. what we need to do is look at where the 
program handles the data coming in.

Art

**Comment by scotthibbs** [comment]
I'm sorry Art, I figured it out. Win10 now blocks port 80. So I set it to 55555 and it works. I should have came back and closed this issue.

**Comment by scotthibbs** [comment]
Win10 now blocks port 80. So I set it to 55555 and it works. I'll upload the new file soon.
