### ISSUE TITLE
winter field day

### ISSUE THREAD

**Issue by nouse4anick** [scotthibbs/FDLog_Enhanced#6]
I was wondering if we wanted to add winter field day support to fdlog... the only real change I can see is that it uses i, o, and h instead of a-f for the exchange.

we would have to modify the wasrpt function and maybe a few others where it checks the section and state. I need to read more code, but i think some of the code can be functionalized and condensed so its easier to modify.

**Comment by nouse4anick** [comment]
fyi the line is 1038:
m = re.match(r' *[0-9]+[a-fA-F] +([A-Za-z]{2,4})', i.rept)
I did a test with this and it seems to work:
m = re.match(r' *[0-9]+[a-fiohA-FIOH] +([A-Za-z]{2,4})', i.rept)

I think the only other change that needs to be made is to output a section for the qso's that follows the format that this site is looking for: http://b4h.net/cabforms/winterfieldday_cab3.php

specifically:
Enter your QSO data in this text area, one QSO per line. Each of the fields below must be entered for each QSO. One or more spaces must separate each item in a QSO. All dates and times must be in UTC. If the time of the QSO is not known, enter 1900.
-----------------------------------------------------------
Band Mode Date Time Call-Copied Category-Copied Sec-Copied 
20   ph   1/26 1900 w8d         1o              oh         
-----------------------------------------------------------

modes are ph/cw/di for phone, cw and digital, everything else is accounted for.

**Comment by nouse4anick** [comment]
btw i've spent pretty much all morning making a cabrillo output for winter field day... thinking about expanding it for the VHF contest and maybe fd if I can get a sample output from the website

**Comment by scotthibbs** [comment]
I always submit fd via the website for the extra points without sending the cabrillo. It has been a couple years since I submitted our score, but the website is fill in the blank so not to terrible to do online. I've never worked the VHF event.

Winter FD should be a mode like VHF and FD.  We will still want the checks (m = re.match...) to reflect which mode we are in. This way we can't enter an h in a regular field day contest or the VHF contest. 

Thanks for your efforts! :)

**Comment by nouse4anick** [comment]
I can add the checking in later for the I/O/H and if its WFD or FD or VHF contests. right now however I have the rough 'draft' working and it looks good (i'm trying to get a hold of the contest guys and get clarification on the cabrillo format).

I don't think the WFD has a bonus for web submission, but I'll double check here in a bit.

**Comment by nouse4anick** [comment]
so no bonus for web form submission, I am having a difficult time adding the check in for the exchange... i think i need to find a different place for that... right now i'm trying to add it into the qso parser but the report does both the exchange and the section...

**Comment by nouse4anick** [comment]
Sorry for spamming your inbox about updates, I have one more update to do (add wfd to the initial screen) and then I'll be ready to commit my fork. I got the exchange check (for whatever reason it only works as 1h wwa and not wwa 1h... i don't know if its checked elsewhere but as long as its 1h wwa format its fine!)

**Comment by scotthibbs** [comment]
I believe this has been done.
