### ISSUE TITLE
record edits and recording

### ISSUE THREAD

**Issue by nouse4anick** [scotthibbs/FDLog_Enhanced#7]
So interesting thing happened during the winter field day, we were using one computer to log while the other one ran a copy of fldigi and fdlog_enhanced.... for whatever reason I had to log a contact on the 2nd computer and it made the record number 7.... end of the day I go back and look and see that i need to change the power setting for it to count.

it wouldn't let me edit it as it wasn't a valid record. I look a little closer and the digital computer has that record (#7), and its the only one, and on the logging computer it ALSO has a #7 record! it wouldn't let me edit the record on the logging computer (i suspect that it see's both records and is only trying to edit the first one).

I am unsure if this really needs to be addressed or if a change in the sql statement would help (ie grab data for only the current node)

**Comment by scotthibbs** [comment]
There are several checks here.. 

"tst" or test mode, (allowing a .testq command to generate multiple contacts) is the only way to log a contact without having a power setting etc. Otherwise it will not accept the input into the log and it says why. 
There is a check that the node who placed the log entry can make the change. (those are blue) Others shouldn't be able to edit after the fact without the original node knowing.
Also, before you can edit a record, it looks to see if it is still in the log. Previously edited entries can not be selected for an edit.

It could be one of the above..
Scott

**Comment by nouse4anick** [comment]
so it was in an actual log (19w), I am almost willing to bet that it added it to the database and not the node and thats why I couldn't edit it but when i went into the database it was there.

I'll double check some code and see if I can see any issues that jump out at me

Art

**Comment by scotthibbs** [comment]
I've been thinking about this. Several years ago, we had a node that wasn't connected to the network. They were able to work a dupe and not know it. When they connected to the network, it added the record on all the other machines, even though it was a dupe. 

Maybe we need to have machines that are not connected warn the user not to log. Maybe we keep a temp log until they do connect and have it re-enter all the contacts checking for dupes. This is fixable I think.

**Comment by nouse4anick** [comment]
a 'merge log' function should probably be made. I think the only check 
should be same band/same call. the time doesn't matter nor does any of 
the other info really.

I really need to get back into coding, maybe i'll be able to do that 
soon here, I switched to graveyard shift and I need stuff to do to keep 
me occupied during the night while my family is sleeping.

**Comment by scotthibbs** [comment]
That would be awesome! Guess this would coincide with the network class. Maybe it needs to receive all records first then the merge log dupe check before sharing back. Then when it disconnects it would keep the merge log again. 
Good to hear from you - Scott

**Comment by nouse4anick** [comment]
I think we need to trace how it normally logs over the network, I'm not 
sure if the way it normally logs over the network checks for dups now 
but it wouldn't hurt to check

also, i think we need to check for mode as well, I need to look at all 
the rules but I think you are allowed to work the same person on each 
band 3 times (cw/data/voice), this includes working them on other bands, 
I think winter field day does this but its been a while since i've done 
any contesting (stupid wind blowing my antenna down and the wife not 
letting me put up another dipole!)

**Comment by scotthibbs** [comment]
I think the only dupe check is at input. I'm foggy on how the network function works though. Yes, a person can work each mode to the same station, the program handles this by setting our bands by mode. 

So good to be working on this again.

**Comment by scotthibbs** [comment]
I've ported this to Python 3. I've added dupe checking when doing fills to our to do list.
